name: CodeQL Analysis

on:
  push:
    branches:
      - main

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: javascript

      - name: Build and analyze
        uses: github/codeql-action/analyze@v1

      - name: Upload CodeQL results
        uses: actions/upload-artifact@v2
        with:
          name: codeql-results
          path: ${{ github.workspace }}/codeql-results

  upload-report:
    runs-on: ubuntu-latest
    needs: analyze

    steps:
      - name: Download CodeQL results
        uses: actions/download-artifact@v2
        with:
          name: codeql-results

      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: codeql-report
          path: ${{ github.workspace }}/codeql-results/results.sarif
